# Generated by Django 4.2.16 on 2024-12-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_alter_review_game_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='game_platform',
            field=models.CharField(choices=[('PC', 'PC'), ('PlayStation', 'PlayStation'), ('XBOX', 'XBOX'), ('Nintendo', 'Nintendo'), ('Other', 'Other')], default='PC', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='game_score',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0),
        ),
    ]
