# Generated by Django 4.2.16 on 2024-12-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0015_comment_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="game_platform",
            field=models.CharField(
                choices=[
                    ("PC", "PC"),
                    ("PlayStation", "PlayStation"),
                    ("XBOX", "XBOX"),
                    ("Nintendo", "Nintendo"),
                    ("Mobile", "Mobile"),
                    ("Other", "Other"),
                ],
                default="PC",
                max_length=50,
            ),
        ),
    ]
