# Generated by Django 4.2.16 on 2024-12-11 06:02

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0017_alter_review_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="images",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default="",
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="app_blog/",
            ),
        ),
    ]
