# Generated by Django 4.2.16 on 2024-12-12 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_blog", "0018_alter_review_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="images",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default="Playpoint_logo_icon-removebg-preview_xy8ytf",
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="app_blog/",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
