# Generated by Django 4.2.16 on 2025-01-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0019_alter_review_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
